<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CP.AspNetCore.SignalR.Client.Rx\CP.AspNetCore.SignalR.Client.Rx.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI.Primitives" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Diagnostics" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
    <Using Include="System.Windows" />
    <Using Include="System.Windows.Controls" />
    <Using Include="CP.AspNetCore.SignalR.Client.Rx" />
    <Using Include="Microsoft.AspNetCore.SignalR.Client" />
    <Using Include="ReactiveUI.Primitives" />
    <Using Include="ReactiveUI.Primitives.Extensions" />
    <Using Include="ReactiveUI.Primitives.Disposables.Scope" Alias="Disposable" />
    <Using Include="ReactiveUI.Primitives.Signals.Signal" Alias="Observable" />
  </ItemGroup>

</Project>
