<Project DefaultTargets="Build"
  xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Authors>Chris Pulman</Authors>
    <Description>An Extension of the Microsoft.AspNetCore.SignalR.Client library</Description>
    <Copyright>Copyright © https://github.com/ChrisPulman $([System.DateTime]::Now.ToString(yyyy))</Copyright>
    <IsTestProject>$(MSBuildProjectName.Contains('Tests'))</IsTestProject>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>preview</LangVersion>
    <Configuration>$(TargetFramework)</Configuration>
    <Company>ChrisPulman</Company>
    <Nullable>enable</Nullable>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>Compatibility with .NET 8 / 9 / 10 / 11 and .NET Framework 4.6.2 / 4.7.2 / 4.8 / 4.8.1</PackageReleaseNotes>
    <PackageTags>Microsoft;Extensions;SignalR;Rx;Reactive;ReactiveUI.Primitives;net</PackageTags>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>

    <PackageProjectUrl>https://github.com/ChrisPulman/CP.AspNetCore.SignalR.Client.Rx</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ChrisPulman/CP.AspNetCore.SignalR.Client.Rx</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <!--https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/-->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <!-- Include PDB in the built .nupkg -->
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup>
    <MinVerAutoIncrement>minor</MinVerAutoIncrement>
    <MinVerDefaultPreReleaseIdentifiers>alpha.0</MinVerDefaultPreReleaseIdentifiers>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerMinimumMajorMinor>1.6</MinVerMinimumMajorMinor>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsTestProject)' != 'true'">
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)images\logo.png" Pack="true" PackagePath="\"/>
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="LICENSE" />
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StyleSharp.Analyzers" PrivateAssets="all" />
    <PackageReference Include="PerformanceSharp.Analyzers" PrivateAssets="all" />
    <PackageReference Include="SecuritySharp.Analyzers" PrivateAssets="all" />
    <PackageReference Include="Roslynator.Analyzers" PrivateAssets="All" />
  </ItemGroup>
</Project>
